version: '2'

services:
  web:
    image: nginx
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 3000:3000
    links:
      - front
      - back
  front:
    image: node:9.9.0
    volumes:
      - ./front:/code
    working_dir: /code
    command: sh -c 'yarn install && yarn start'
  back:
    image: openjdk
    volumes:
      - ./back:/code
      - /root/.ivy2
      - /root/.sbt
    working_dir: /code
    command: /code/sbt ~run
    links:
      - db:chorekiller-db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=chorekiller
      - POSTGRES_PASSWORD=chorekiller
      - POSTGRES_DB=chorekiller
